### ISSUE TITLE
Merge & release v0.26c tag from upstream

### ISSUE THREAD

**Issue by jirislav** [jirislav/mailinabox#10]
My last attempt to merge the tag resulted in a broken installation, so I'm going to have to take a deeper look into this.

Expect this to be done until the end of this weekend.

**Comment by derekslenk** [comment]
Is there anything you need help with or do you just need time?

**Comment by jirislav** [comment]
Tonight I'm going to fix this :)

**Comment by jirislav** [comment]
Okay, it's [done](https://github.com/jirislav/mailinabox/releases/tag/v0.26c-ubuntu16) :) (had to stop supporting automated installation of Nextant & Solr - use at your own risk)
