### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by project-ext** [jirislav/mailinabox#12]
Could do with adding support for removing any leftover mail in a box (14.04) install attempts.

**Comment by project-ext** [comment]
following on -  apt-get update fails if 14.04 mail in a box setup was run.

**Comment by jirislav** [comment]
Can you please paste here the output of `apt-get update`?

**Comment by project-ext** [comment]
FAILED: apt-get update
-----------------------------------------
Ign:1 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
Ign:3 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial Release
Ign:4 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main i386 Packages
Ign:5 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main all Packages
Ign:6 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US
Ign:7 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en
Ign:8 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US.UTF-8
Ign:4 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main i386 Packages
Ign:5 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main all Packages
Ign:6 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US
Ign:7 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en
Ign:8 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US.UTF-8
Ign:4 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main i386 Packages
Ign:5 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main all Packages
Ign:6 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US
Hit:9 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Ign:7 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en
Hit:10 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign:8 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US.UTF-8
Ign:4 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main i386 Packages
Ign:5 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main all Packages
Ign:6 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US
Ign:7 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en
Ign:8 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US.UTF-8
Ign:4 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main i386 Packages
Ign:5 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main all Packages
Ign:6 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US
Ign:7 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en
Ign:8 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US.UTF-8
Err:4 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main i386 Packages
  404  Not Found
Ign:5 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main all Packages
Hit:11 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
Ign:6 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US
Ign:7 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en
Ign:8 http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial/main Translation-en_US.UTF-8
Hit:12 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists...
W: The repository 'http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/mail-in-a-box/ppa/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jirislav** [comment]
How did you call install for 14.04 anyway? Wrong tag?

**Comment by project-ext** [comment]
curl -s https://mailinabox.email/setup.sh | sudo bash

**Comment by jirislav** [comment]
Oh, that's sure a way to damage the installation. This should be launched only at Ubuntu 14, not 16.

You may try running this remedy:
```bash
rm -rf $HOME/mailinabox
```

And then following the [Quick Install](https://github.com/jirislav/mailinabox#quick-install) guide for Ubuntu 16

**Comment by jirislav** [comment]
Did that help you? Can we close this issue?

**Comment by jirislav** [comment]
Ok, you're not responding, so I'm closing this issue for now. 

Remember that the only method to install MIAB on Ubuntu 16 is to follow appropriate installation guide.
