### ISSUE TITLE
SPREED not found!

### ISSUE THREAD

**Issue by itsbhanusharma** [jirislav/mailinabox#16]
I'm struggling with install for last 3 hours and it is always stuck at this!

```
FAILED: sudo -u www-data php /usr/local/lib/owncloud/console.php app:enable spreed
-----------------------------------------
spreed not found
-----------------------------------------
```

**Comment by istr** [comment]
Do you happen to try the installation after upgrading (do-release-upgrade) from 14.04 to 16.04?
I Had the same issue on an upgraded machine.
Please try to purge / move all packages from /usr/local/lib (make a backup first!) and then run the setup again.
I also had to remove all pip packages and let setup/start.sh re-install them.
```bash
sudo mv /usr/local/lib /usr/local/lib-OLD
sudo apt-get purge python3-pip python-pip python-pip-whl
sudo apt-get autoremove
sudo setup/start.sh
```

**Comment by itsbhanusharma** [comment]
Yes, It was a migration from 14.04 to 16.04, Better yet, my old stock miab was left installed (I only removed the /root/mailinabox folder and replaced it with the script provided in this repo.

I managed to install it by manually copying spreed (got the version from start.sh file) into the relative directory. I had some issues with python venv as well and that too was fixed with the help of internet!

I however wonder why is this script no aware of users migrating from 14.04 to 16.04!

**Comment by istr** [comment]
This is by design. Major upgrades are not supported due to the added complexity. There are very easy means to backup, restore and move your running box to a fresh instance. See:
https://mailinabox.email/
https://mailinabox.email/guide.html
https://mailinabox.email/maintenance.html

So you better rather

- create a fresh box
- install a fresh miab there
- backup the old box
- restore it in the new box

than trying to migrate an existing box.

**Comment by itsbhanusharma** [comment]
I could have gone with that approach but the mails we exchange between our corporate and my personal email (Hosted on MIAB) get messed up as soon as the IP changes so it is really a matter of choosing between uninterrupted flow or spending a weekend diagnosing delivery for me!

I chose to YOLO it!

**Comment by istr** [comment]
Good point -- but nowadays even most of the cheapest hosting providers (e.g. [scaleway](https://www.scaleway.com/baremetal-cloud-servers/), where I am running one of my miab instances on an ARM C1 server) provide failover IP facilities. Maybe you might consider to go through the pain once, and move your setup to an ISP that provides failover IPs and then be happy with [blue green deployment](https://martinfowler.com/bliki/BlueGreenDeployment.html) of your miab instances, now and forever.

But otoh, YOLO is a valid argument, too. :+1:

**Comment by itsbhanusharma** [comment]
Hmmm... Interesting! I'd have to dig into that blue/green thing a bit more I guess! I had a DO failover IP for the node but I had never been able to set it up to work as a secondary IP! all mail exchange happens through the droplet's primary IP only!  :( any suggestions about that?
