### ISSUE TITLE
Apache Solr (fulltext search engine for Nextcloud using nextant app) is not running (port 8983).

### ISSUE THREAD

**Issue by cndanili** [jirislav/mailinabox#2]
Hi,

First, I'd like to thank you for forking that project to Ubunt 16.04.

I have encountered this issue after I restored my backups. I tried reruning setup/start.sh to fix that, but fialed.

The error message is down below.

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "nextant" namespace.

FAILED: sudo -u www-data php /usr/local/lib/owncloud/occ nextant:index --background --unlock
-----------------------------------------
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "nextant" namespace.
y backups, then I tried rerunning setup/start.sh to fix this, but failed.

**Comment by jirislav** [comment]
Hi,

I'm glad you like porting MIAB ^^.

Have you tried running `setup/start.sh` with `INSTALL_NEXTANT=no` environment variable?

Full command to try:
```bash
INSTALL_NEXTANT=no setup/start.sh
```

You should be all good without nextant, it just uses Solr to improve searching across Nextcloud. WIthout Nextant there will be Nextcloud's default search engine enabled, so you will still be able to search :)

**Comment by cndanili** [comment]
Sorry for the late reply.
Issue is still ongong  after I pasted your command in putty.

> Updating system packages...
> Installing system packages...
> Initializing system random number generator...
> Firewall is active and enabled on system startup
> Installing nsd (DNS server)...
> Installing Postfix (SMTP server)...
> Installing Dovecot (IMAP server)...
> Installing OpenDKIM/OpenDMARC...
> Installing SpamAssassin...
> Installing Nginx (web server)...
> Installing Roundcube (webmail)...
> Installing Nextcloud (contacts/calendar)...
> Nextcloud is already latest version
> Installing Z-Push (Exchange/ActiveSync server)...
> Installing Mail-in-a-Box system management daemon...
> Installing Munin (system monitoring)...
> updated DNS: OpenDKIM configuration
> No TLS certificates could be provisoned at this time:

Yes, I knew it's ok to run the MIAB without NEXTANT, but I like the looking of all green system status checks.
I'm gonna  just leave it, it's no big deal.

Thanks for your answer.

**Comment by jirislav** [comment]
I'm sorry I couldn't help you with your problem. I've created [an issue](https://github.com/jirislav/mailinabox/issues/5) to remove Solr from watched services so that you can see all green system status checks if you intentionally install MIAB without Nextand, thus Solr :smiley: . So I hope you will soon see all checks green.

Btw, what procedure did you take to restore your backups? I suppose that if you have installed MIAB on a clean Ubuntu, you wouldn't run into this issue.

**Comment by cndanili** [comment]
I restored my backups accroding to [offical maintenance guide](https://mailinabox.email/maintenance.html).The backups was literally successful expect for the notifacation of "missing serect key" when system status check commnad executed.

Maybe backup is the cause of that issue.

**Comment by derekslenk** [comment]
I just upgraded from 0.26b to 0.26c, and have never done INSTALL_NEXTANT=no, and have never seen it with SOLR as a failed status check before.

Is it just showing up now because of the upgrade to 0.26c?

**Comment by jirislav** [comment]
@derekslenk the thing is that installing Nextant with Solr showed up to be broken way too often, which is why I made `INSTALL_NEXTANT=no` the default when upgrading/installing MIAB since the version of 0.26c.

I now have to fix [this issue](https://github.com/jirislav/mailinabox/issues/5) to stop sending warnings about solr not running.
