### ISSUE TITLE
How to keep this project alive (fork, remote release merge, ..)

### ISSUE THREAD

**Issue by albialbi** [jirislav/mailinabox#21]
jirislav will you update to 0.27, or can you explain how to do that.
Als long as there is no miab for Ubuntu 18, I hope you continue this project.
Thanks for your work!

**Comment by jirislav** [comment]
1) Fork this fork
2) Rename branch `old-master` to `master` (and force push it)
3) Add main remote and fetch all of it's tags

```bash
git remote add mail-in-a-box https://github.com/mail-in-a-box/mailinabox.git
git fetch --all --prune
```

4) Choose a release you want to merge and merge it

```bash
git merge mail-in-a-box/v0.27
```

5) Test the functionality
6) Push it to your `master` branch

**Comment by jirislav** [comment]
And then you can optionally add the URL of your fork into this issue, I'll propagate it into the main README so that others can start using your fork.
