### ISSUE TITLE
Install Issues and workrounds

### ISSUE THREAD

**Issue by broberson** [jirislav/mailinabox#3]
Installing Solr, I hit a file access error trying to work with an ini file that apparently didn't exist - or maybe that part of the install wasn't running as root. After 60 seconds the process got killed off and the install continued. Subsequent runs of the setup script did not trigger this error message, and it doesn't seem fatal.

Next thing I hit was that ZPush failed to install – Seems there's a new hash?
Replacing the old one (aae5093212ac0b7d8bf2d79fd5b87ca5bbf091cb) with the one I get from the script (66b1613faef61590836682ff1a43d559827fe08b) worked.

The next problem was an error when installing the Mail-In-A-Box Management Daemon, where the command `pip2 install --upgrade boto` where it complained there was no module named pkg_resources. Running `curl https://bootstrap.pypa.io/ez_setup.py | python` and restarting the setup solved that. I don't know offhand which setup script might need to be changed to make that work.

After that, everything went smoothly. No idea if this is Ubuntu 16.04 related or if the same issues might crop up in an unmodified MIAB install - but I figured it'd help if you knew about it.

Thanks for making this available - very cool of you.

**Comment by jirislav** [comment]
Thank you @broberson for taking your time to submit this issue. I'm going to fix those problems right away.

**Comment by jirislav** [comment]
Okay, that should be all fixed for now (except for that Solr part - I couldn't determine the problem, so I guess I'll have to find the problem myself after I manage testing MIAB via docker on local machine)

**Comment by jirislav** [comment]
Oh & btw, I'm glad you like making this available ^^
