### ISSUE TITLE
Mailinabox v0.26 has been released

### ISSUE THREAD

**Issue by derekslenk** [jirislav/mailinabox#8]
Looks like 1 important security fix. I may look into how to contribute to this project myself

https://github.com/mail-in-a-box/mailinabox/blob/v0.26/CHANGELOG.md#changelog

**Comment by jirislav** [comment]
I'm sorry, but I'm right now being very busy. I know about that security fix & I plan to merge it tonight +/- at UTC 18:00.

**Comment by jirislav** [comment]
So I've merged the upstream version, you can upgrade with:
```bash
cd mailinabox
git fetch --all
git checkout v0.26-ubuntu16
setup/start.sh
```

**Comment by derekslenk** [comment]
OH man that was fast, I did not expect that right away.

Thank you!
