### ISSUE TITLE
updating mailinabox

### ISSUE THREAD

**Issue by ghost** [jirislav/mailinabox#9]
Hi @jirislav 

Thanks for your work. 

Here is my question. Can I update Ubuntu via "apt-get update && apt-get dist-upgrade" or would this break something?

thanks and cheers

**Comment by jirislav** [comment]
Hi @himbeere 

I'm glad you like my work.

About upgrading to newer version of Ubuntu - I haven't tried it. It is possible that some features will be limited or not available at all. But it's also possible it will work flawlessly without any hassle. Those features are:
* local + public DNS
* Roundcube
* Munin
* Nextcloud
* Dovecot (without lucene)
* Postfix
* SpamAssassin
* Fail2ban
* DKIM (yes, DNSSEC also tested)
* Web administration
* SSL provisioning

Btw if you're running on a virtual machine, you may easily create a snapshot before migration & if something goes wrong, just easily restore it back. So this could be one way to safely try it out.

**Comment by ghost** [comment]
I see. So the recommended way is to use setup/start.sh to update the system whenever you release a new version?

I will try to run apt-get dist-upgrade after making a snapshot of the VM.

thanks

**Comment by jirislav** [comment]
Whenever I release a new version, the recommended way to update is to follow [the release description](https://github.com/jirislav/mailinabox/releases)

**Comment by jirislav** [comment]
So, how did you do? Can we close this issue?

**Comment by ghost** [comment]
I guess we can. Thanks again.

**Comment by jirislav** [comment]
Ok, I'm glad I've helped you :)

... btw did you succeed upgrading?

**Comment by ghost** [comment]
Yes. Worked like a charm.

**Comment by jirislav** [comment]
That's very nice! :) Thanks for testing this out ;)
